[package]
name = "tot_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
#chrono = "0.4"
quote = "1"
proc-macro2 = "1.0"
log = "0.4"
